name: restaurant-inspection-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - scikit-learn
  - matplotlib
  - python-dotenv
  - tqdm
  - black
  - ipykernel
  - pip:
      - sqlfluff
      - black[jupyter]